- src/test/java/com/simasforum/SimasForum/controller/ThreadControllerTest.java
add test for new thread (showAddThreadPage_ok, showAddThreadPage_html)
> add test for new thread

- src/test/java/com/simasforum/SimasForum/service/ThreadServiceTest.java
> fix search thread test

- pom.xml
- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/controller/UserController.java
- src/main/resources/application.properties
- src/main/resources/templates/dashboard.html
- src/main/resources/templates/fragments/nav.html
- src/main/resources/templates/login.html
update user login using http session, controller update for dashboard, and session use example on ui
> update user login with session

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/model/Thread.java
- src/main/java/com/simasforum/SimasForum/service/ThreadService.java
- src/main/resources/db/changelog/changes/v0001.sql
- src/main/resources/templates/thread.html
- src/test/java/com/simasforum/SimasForum/controller/ThreadControllerTest.java
- src/test/java/com/simasforum/SimasForum/service/ThreadServiceTest.java
update thread controller so it works with user login
> update thread controller with user

- src/main/resources/templates/login.html
- src/main/resources/templates/register.html
fix redirect from login to register n vice versa
> fix redirect from login to register

- src/main/java/com/simasforum/SimasForum/controller/UserController.java
- src/main/java/com/simasforum/SimasForum/repository/UserRepository.java
- src/main/java/com/simasforum/SimasForum/service/UserService.java
- src/test/java/com/simasforum/SimasForum/service/UserServiceTest.java
fix email not exist crashes and email ignore case
> fix email not exist crashes and email ignore case

- src/main/resources/application.properties
ganti properties session timeout dan cookie age
> update session timeout properties

- src/main/java/com/simasforum/SimasForum/model/Reply.java
- src/main/java/com/simasforum/SimasForum/repository/ReplyRepository.java
- src/main/resources/db/changelog/changes/v0002.sql
> reply model,repository,sql

- src/main/java/com/simasforum/SimasForum/model/Reply.java
- src/main/java/com/simasforum/SimasForum/repository/ReplyRepository.java
- src/main/java/com/simasforum/SimasForum/service/ReplyService.java
- src/main/resources/db/changelog/changes/v0002.sql
- src/test/java/com/simasforum/SimasForum/service/ReplyServiceTest.java
Reply service dan service test dan perbaiki sql
> Reply service dan service test

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/model/Thread.java
- src/main/java/com/simasforum/SimasForum/model/User.java
- src/main/resources/db/changelog/changes/v0001.sql
- implements model relation between thread and user, 
- mock mythread controller(to be replaced)
> implement model relation for thread and user

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/model/Reply.java
- src/main/java/com/simasforum/SimasForum/model/Thread.java
- src/main/java/com/simasforum/SimasForum/repository/ThreadRepository.java
- src/main/java/com/simasforum/SimasForum/service/ReplyService.java
- src/main/java/com/simasforum/SimasForum/service/ThreadService.java
- src/main/resources/db/changelog/changes/v0001.sql
- src/main/resources/db/changelog/changes/v0002.sql
- src/main/resources/templates/dashboard.html
- src/main/resources/templates/thread.html
- src/test/java/com/simasforum/SimasForum/controller/ThreadControllerTest.java
- src/test/java/com/simasforum/SimasForum/service/ReplyServiceTest.java
- src/test/java/com/simasforum/SimasForum/service/ThreadServiceTest.java
this contains refactor for model relation and attribute naming
> refactor models

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/repository/ReplyRepository.java
- src/main/java/com/simasforum/SimasForum/service/ReplyService.java
- src/test/java/com/simasforum/SimasForum/service/ReplyServiceTest.java
- src/test/java/com/simasforum/SimasForum/service/ThreadServiceTest.java
update reply service and thread test error
> update reply service and test error

- src/main/java/com/simasforum/SimasForum/service/ThreadService.java
> fix up and down vote

- src/main/resources/templates/thread.html
> add color button when onclick

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
fix change button color onclick
> fix change button color onclick

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/test/java/com/simasforum/SimasForum/controller/ThreadControllerTest.java
contains delete reply controller and unit test
> add delete reply controller

- src/test/java/com/simasforum/SimasForum/controller/ThreadControllerTest.java
add session attribute to mockmvc for thread controller test
> update thread controller test

- src/main/java/com/simasforum/SimasForum/service/ReplyService.java
- src/main/resources/templates/thread.html
add controller to create reply
> add controller to create reply

- src/main/java/com/simasforum/SimasForum/controller/ReplyController.java
> add reply controller

- src/main/java/com/simasforum/SimasForum/controller/ReplyController.java
- src/main/java/com/simasforum/SimasForum/service/ReplyService.java
- src/test/java/com/simasforum/SimasForum/controller/ReplyControllerTest.java
- src/test/java/com/simasforum/SimasForum/service/ReplyServiceTest.java
contains junit for reply controller and few syntax changes
> add unit test for reply controller

- src/main/java/com/simasforum/SimasForum/controller/VoteController.java
- src/test/java/com/simasforum/SimasForum/controller/ReplyControllerTest.java
fix reply test and vote controller
> fix reply test and vote controller

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/controller/VoteController.java
- src/main/java/com/simasforum/SimasForum/service/VoteService.java
- src/main/resources/templates/thread.html
> Feature/reply UI

- .github/workflows/dpl.yml
update dpl yml buat testingnya moga" jalan
> edit dpl.yml

- .github/workflows/dpl.yml
> update test action

- .github/workflows/dpl.yml
> update yml test

- pom.xml
> add jacoco to pom

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/model/Reply.java
- src/main/java/com/simasforum/SimasForum/model/Thread.java
- src/main/resources/templates/dashboard.html
- src/main/resources/templates/fragments/nav.html
update cascade for thread and reply to vote
> update cascade for thread and reply to vote

- lombok.config
- pom.xml
- src/main/java/com/simasforum/SimasForum/controller/VoteController.java
- src/main/java/com/simasforum/SimasForum/model/Thread.java
- src/main/java/com/simasforum/SimasForum/model/User.java
- src/main/java/com/simasforum/SimasForum/service/ReplyService.java
- src/main/java/com/simasforum/SimasForum/service/VoteService.java
- src/test/java/com/simasforum/SimasForum/controller/VoteControllerTest.java
- src/test/java/com/simasforum/SimasForum/service/ReplyServiceTest.java
- src/test/java/com/simasforum/SimasForum/service/VoteServiceTest.java
update unit tests and add lombok.config file for better coverage
> update unit tests for better coverage

- src/test/java/com/simasforum/SimasForum/controller/VoteControllerTest.java
- src/test/java/com/simasforum/SimasForum/service/VoteServiceTest.java
fix user constructors on unit testing
> fix user constructors on unit testing

- src/main/java/com/simasforum/SimasForum/controller/PinController.java
- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/controller/UserController.java
- src/main/java/com/simasforum/SimasForum/model/Pin.java
- src/main/java/com/simasforum/SimasForum/model/Reply.java
- src/main/java/com/simasforum/SimasForum/model/Thread.java
- src/main/java/com/simasforum/SimasForum/repository/PinRepository.java
- src/main/java/com/simasforum/SimasForum/service/PinService.java
update model pin and thread for pin thread
> thread pin update

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/service/PinService.java
- src/main/resources/templates/dashboard.html
update pin thread to dashboard
> update pin thread to dashboard

- src/main/resources/templates/thread.html
> validasi pin reply

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/resources/templates/search_thread_result.html
update search page shows pinned thread
> update search page shows pinned thread

- src/main/java/com/simasforum/SimasForum/controller/PinController.java
- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/java/com/simasforum/SimasForum/service/PinService.java
- src/test/java/com/simasforum/SimasForum/controller/ThreadControllerTest.java
- src/test/java/com/simasforum/SimasForum/controller/UserControllerTest.java
- src/test/java/com/simasforum/SimasForum/service/PinServiceTest.java
update unit test pin service and controllers
> update unit test pin service and controllers

- src/main/java/com/simasforum/SimasForum/service/VoteService.java
- src/test/java/com/simasforum/SimasForum/controller/ThreadControllerTest.java
- src/test/java/com/simasforum/SimasForum/service/PinServiceTest.java
> sonar complexity fix

- src/main/java/com/simasforum/SimasForum/controller/ThreadController.java
- src/main/resources/templates/dashboard.html
- src/main/resources/templates/fragments/nav.html
- src/main/resources/templates/fragments/reply-action.html
- src/main/resources/templates/fragments/sidebar.html
- src/main/resources/templates/search_thread_result.html
- src/main/resources/templates/thread.html
> re-deploy to main

- src/main/resources/templates/dashboard.html
- src/main/resources/templates/fragments/nav.html
- src/main/resources/templates/fragments/reply-action.html
- src/main/resources/templates/fragments/sidebar.html
- src/main/resources/templates/search_thread_result.html
- src/main/resources/templates/thread.html
> re-deploy again to main

- src/main/java/com/simasforum/SimasForum/controller/UserController.java
- src/test/java/com/simasforum/SimasForum/controller/PinControllerTest.java
- src/test/java/com/simasforum/SimasForum/service/ReportServiceTest.java
> update unit test for coverage
